---
dependencies:
    - name: subtest
      version: 0.1.0
      repository: "file://charts/subtest"
      alias: second
    
    - name: subtest
      version: 0.1.0
      repository: "file://charts/subtest"
      alias: barabuda